/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GridList.java
 *
 * Created on 08/12/2011, 09:51:41
 */
package bc.ui.swing.lists;

import bc.ui.swing.visuals.Visual;
import java.awt.GridLayout;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author bennyl
 */
public class GridList extends javax.swing.JPanel {

    GridLayout grid;
    ComponentBuilder cbuild = new ComponentBuilder.DefaultComponentBuilder();
    
    /** Creates new form GridList */
    public GridList() {
        initComponents();
        grid = (GridLayout) content.getLayout();
    }

    public ComponentBuilder getComponentBuilder() {
        return cbuild;
    }

    public void setComponentBuilder(ComponentBuilder cbuild) {
        this.cbuild = cbuild;
    }
    
    public void setVgap(int vgap) {
        grid.setVgap(vgap);
    }

    public void setHgap(int hgap) {
        grid.setHgap(hgap);
    }

    public void setColumns(int cols) {
        grid.setColumns(cols);
    }

    public int getVgap() {
        return grid.getVgap();
    }

    public int getRows() {
        return grid.getRows();
    }

    public int getHgap() {
        return grid.getHgap();
    }

    public int getColumns() {
        return grid.getColumns();
    }

    public void setItems(List<Visual> items){
        content.removeAll();
        content.setVisible(false);
        for (Visual item : items){
            content.add(cbuild.build(item));
        }
        content.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        content = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        scroll.setBorder(null);
        scroll.setOpaque(false);

        content.setLayout(new java.awt.GridLayout());
        scroll.setViewportView(content);

        add(scroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
