/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LabelList.java
 *
 * Created on 28/11/2011, 01:33:09
 */
package bc.ui.swing.lists;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.util.LinkedHashMap;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author bennyl
 */
public class LabelList extends javax.swing.JPanel {

    protected LinkedHashMap<Object, JComponent> items = new LinkedHashMap<Object, JComponent>();

    /** Creates new form LabelList */
    public LabelList() {
        initComponents();
    }

    public void remove(Object item) {
        JComponent box = items.remove(item);
        remove(box);
    }

    public void clear() {
        removeAll();
        items.clear();
    }

    public void addAll(List items) {
        for (Object i : items) {
            add(i);
        }
    }

    public void add(final Object item) {

        final JComponent comp = createComponentFor(item);
        items.put(item, comp);

        GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.BOTH;
        add(comp, gbc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private JComponent createComponentFor(Object item) {
        JLabel j = new JLabel(item.toString());
        j.setForeground(getForeground());
        j.setBorder(new EmptyBorder(2,2,2,2));
        return j;
    }
}
