/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NoDataPanel.java
 *
 * Created on 26/11/2011, 17:34:16
 */
package bc.ui.swing.useful;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JComponent;

/**
 *
 * @author bennyl
 */
public class DataPanel extends javax.swing.JPanel {

    /** Creates new form NoDataPanel */
    public DataPanel() {
        initComponents();
        unSetData();
    }

    public void setNoDataForeColor(Color color){
        noDataLabel.setForeground(color);
    }
    
    public Color getNoDataForeColor(){
        return noDataLabel.getForeground();
    }
    
    public String getNoDataText(){
        return noDataLabel.getText();
    }
    
    public void setNoDataText(String ndt){
        noDataLabel.setText(ndt);
    }
    
    public void setData(JComponent data) {
        unSetData();
        this.data.removeAll();
        this.data.add(data, BorderLayout.CENTER);
        ((CardLayout) getLayout()).show(this, "DATA");
    }

    public final void unSetData() {
        this.data.removeAll();
        ((CardLayout) getLayout()).show(this, "NO_DATA");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        noData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        noDataLabel = new javax.swing.JLabel();
        data = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.CardLayout());

        noData.setOpaque(false);
        noData.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/no-data.png"))); // NOI18N
        noData.add(jLabel1, new java.awt.GridBagConstraints());

        noDataLabel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        noDataLabel.setText("There Is No Data To Show");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        noData.add(noDataLabel, gridBagConstraints);

        add(noData, "NO_DATA");

        data.setOpaque(false);
        data.setLayout(new java.awt.BorderLayout());
        add(data, "DATA");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel noData;
    private javax.swing.JLabel noDataLabel;
    // End of variables declaration//GEN-END:variables
}
