/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConstraintTable.java
 *
 * Created on 30/11/2011, 00:35:09
 */
package bc.ui.swing.tables;

import bc.dsl.SwingDSL;
import java.util.Enumeration;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author bennyl
 */
public class ConstraintTable extends javax.swing.JPanel {

    /** Creates new form ConstraintTable */
    public ConstraintTable() {
        initComponents();
        table.setDefaultRenderer(Object.class, new ConstraintTableRenderer());
    }
    
    public static void main(String[] args){
        SwingDSL.showInFrame(new ConstraintTable());
    }

    public JTable getTable() {
        return table;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        table = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);

        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"5", "7", "2", "1"},
                {"6", "0", "0", "0"},
                {"0", "6", "5", "7"},
                {"0", "0", "3", "2"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setFillsViewportHeight(true);
        table.setGridColor(new java.awt.Color(153, 153, 153));
        table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        table.setRowHeight(22);
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        jPanel1.add(table, new java.awt.GridBagConstraints());

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
