/* 
 * The MIT License
 *
 * Copyright 2016 Benny Lutati.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package bgu.dcr.az.dev.ui;

import java.awt.Component;
import java.io.PrintWriter;
import java.io.StringWriter;
import javax.swing.JPanel;

/**
 *
 * @author kdima85
 */
public class ExceptionDialog extends javax.swing.JDialog {

    /** Creates new form MessageDialog */
    public ExceptionDialog(java.awt.Frame parent, boolean modal, String desc, String whatToDo, Exception ex, boolean recoverable) {
        super(parent, modal);
        initComponents();
        this.descriptionLabel.setText(desc);
        this.whatToDoLabel.setText(whatToDo);
        
        StringWriter sw = new StringWriter();
        ex.printStackTrace(new PrintWriter(sw));
        
        this.advancedLabel.setText(sw.toString());
        this.advancedLabel.setVisible(false);
        if (recoverable) {
            this.exitButton.setText("OK, get me out of here!");
        } else {
            this.exitButton.setText("Damn, close the program!");
        }
        
        this.advancedPanel.setVisible(false);
//        this.advancedLabel.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    public static void showRecoverable(String title, String whatToDo, Exception ex){
        ExceptionDialog d = new ExceptionDialog(null, true, title, whatToDo, ex, true);
        d.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        descriptionLabel = new org.jdesktop.swingx.JXLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        whatToDoLabel = new org.jdesktop.swingx.JXLabel();
        jPanel13 = new javax.swing.JPanel();
        advancedButton = new javax.swing.JButton();
        advancedPanel = new javax.swing.JPanel();
        advancedScrollPanel = new javax.swing.JScrollPane();
        advancedLabel = new javax.swing.JTextArea();
        spacer = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(560, 300));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(560, 300));
        jPanel1.setMinimumSize(new java.awt.Dimension(560, 300));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(560, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(186, 185, 185)));
        jPanel2.setMinimumSize(new java.awt.Dimension(108, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(108, 60));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/exception.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(jLabel1, gridBagConstraints);

        progressLabel.setFont(new java.awt.Font("Consolas", 1, 18));
        progressLabel.setText("Something Went Wrong...");
        progressLabel.setDoubleBuffered(true);
        progressLabel.setMaximumSize(new java.awt.Dimension(70, 22));
        progressLabel.setMinimumSize(new java.awt.Dimension(70, 22));
        progressLabel.setPreferredSize(new java.awt.Dimension(70, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(progressLabel, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel11.setBackground(new java.awt.Color(120, 120, 120));
        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 14));
        jLabel4.setForeground(new java.awt.Color(210, 233, 255));
        jLabel4.setText("Exception description : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        jPanel11.add(jLabel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(jPanel11, gridBagConstraints);

        jPanel15.setBackground(new java.awt.Color(120, 120, 120));
        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.GridBagLayout());

        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setText("jXLabel2");
        descriptionLabel.setFont(new java.awt.Font("Consolas", 0, 12));
        descriptionLabel.setLineWrap(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel15.add(descriptionLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(jPanel15, gridBagConstraints);

        jPanel12.setBackground(new java.awt.Color(120, 120, 120));
        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridBagLayout());

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 14));
        jLabel5.setForeground(new java.awt.Color(210, 233, 255));
        jLabel5.setText("What can you do ?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        jPanel12.add(jLabel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(jPanel12, gridBagConstraints);

        jPanel16.setBackground(new java.awt.Color(120, 120, 120));
        jPanel16.setOpaque(false);
        jPanel16.setLayout(new java.awt.GridBagLayout());

        whatToDoLabel.setForeground(new java.awt.Color(255, 255, 255));
        whatToDoLabel.setText("jXLabel2");
        whatToDoLabel.setFont(new java.awt.Font("Consolas", 0, 12));
        whatToDoLabel.setLineWrap(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel16.add(whatToDoLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(jPanel16, gridBagConstraints);

        jPanel13.setBackground(new java.awt.Color(120, 120, 120));
        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.GridBagLayout());

        advancedButton.setBackground(null);
        advancedButton.setText("Advanced");
        advancedButton.setOpaque(false);
        advancedButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advancedButtonMouseClicked(evt);
            }
        });
        advancedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                advancedButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        jPanel13.add(advancedButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(jPanel13, gridBagConstraints);

        advancedPanel.setBackground(new java.awt.Color(120, 120, 120));
        advancedPanel.setOpaque(false);
        advancedPanel.setLayout(new java.awt.BorderLayout());

        advancedLabel.setColumns(20);
        advancedLabel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        advancedLabel.setRows(5);
        advancedScrollPanel.setViewportView(advancedLabel);

        advancedPanel.add(advancedScrollPanel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(advancedPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(spacer, gridBagConstraints);

        jPanel14.setBackground(new java.awt.Color(120, 120, 120));
        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridBagLayout());

        exitButton.setBackground(null);
        exitButton.setText("jButton1");
        exitButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        exitButton.setOpaque(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 3);
        jPanel14.add(exitButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel3.add(jPanel14, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void advancedButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advancedButtonMouseClicked
    this.advancedLabel.setVisible(true);
}//GEN-LAST:event_advancedButtonMouseClicked
    
private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
}//GEN-LAST:event_exitButtonMouseClicked
    
private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
    this.setVisible(false);
}//GEN-LAST:event_exitButtonActionPerformed

private void advancedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advancedButtonActionPerformed
    // TODO add your handling code here:
    this.setSize((int)this.getSize().getWidth(),500 );
    this.spacer.setVisible(false);
    this.advancedPanel.setVisible(true);
}//GEN-LAST:event_advancedButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advancedButton;
    private javax.swing.JTextArea advancedLabel;
    private javax.swing.JPanel advancedPanel;
    private javax.swing.JScrollPane advancedScrollPanel;
    private org.jdesktop.swingx.JXLabel descriptionLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JLabel spacer;
    private org.jdesktop.swingx.JXLabel whatToDoLabel;
    // End of variables declaration//GEN-END:variables
}
